version: '3.9'

services:
  web:
    build: .
    command: [ "sh", "-c", "sleep 5 && python /app/init_db.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload" ]

    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
